global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: slack-alerts

receivers:
- name: 'slack-alerts'
  slack_configs:
  - api_url: ##provide your slack channel here
    channel: '#cloudteam'  # Replace with the name of your Slack channel (e.g., #general)
    send_resolved: true
    http_config:
      bearer_token: # Replace with the access token you obtained from Slack

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
